// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGjvQbH-Pzj3B7Jc7HWaEUsScYWZZO2cs',
    appId: '1:1039724275291:web:f579435e01764191ce817e',
    messagingSenderId: '1039724275291',
    projectId: 'flutterfoodorderproject',
    authDomain: 'flutterfoodorderproject.firebaseapp.com',
    storageBucket: 'flutterfoodorderproject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWJs0W5iJN-PvpmUDfz8s2HCiQDFRSC-w',
    appId: '1:1039724275291:android:3c1f7f0d1b0ad55bce817e',
    messagingSenderId: '1039724275291',
    projectId: 'flutterfoodorderproject',
    storageBucket: 'flutterfoodorderproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC--fqMdHFD7J7QOb-s_UmCK85rt7zqhDI',
    appId: '1:1039724275291:ios:1bd36e69bfdc936ace817e',
    messagingSenderId: '1039724275291',
    projectId: 'flutterfoodorderproject',
    storageBucket: 'flutterfoodorderproject.appspot.com',
    iosClientId: '1039724275291-qo9rd6unuu7ocmk41655bvlrda3a1ee5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFoodorder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC--fqMdHFD7J7QOb-s_UmCK85rt7zqhDI',
    appId: '1:1039724275291:ios:1bd36e69bfdc936ace817e',
    messagingSenderId: '1039724275291',
    projectId: 'flutterfoodorderproject',
    storageBucket: 'flutterfoodorderproject.appspot.com',
    iosClientId: '1039724275291-qo9rd6unuu7ocmk41655bvlrda3a1ee5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFoodorder',
  );
}
